version: "3.3"

services:
  etcd-dev:
    image: quay.io/coreos/etcd:v3.5.4
    container_name: etcd-${USER}
    restart: "no"
    network_mode: "host"
    volumes:
      - ./data:/etcd-data
    command:
      - /usr/local/bin/etcd
      - --name=s1
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:22379
      - --advertise-client-urls=http://0.0.0.0:22379
      - --listen-peer-urls=http://0.0.0.0:22380
      - --initial-advertise-peer-urls=http://0.0.0.0:22380
      - --initial-cluster=s1=http://0.0.0.0:22380
      - --initial-cluster-token=tkn
      - --initial-cluster-state=new
      - --log-level=info
      - --logger=zap
      - --log-outputs=stderr
