version: "3.3"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    volumes:
      #- ./certs:/usr/share/elasticsearch/config/certs
      - ./data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

