version: "3.3"

services:
  jaeger-dev:
    image: jaegertracing/all-in-one:1.30
    container_name: jaeger-dev-${USER}
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "15775:5775"
      - "16831:6831"
      - "16832:6832"
      - "15778:5778"
      - "26686:16686" # UI
      - "24250:14250"
      - "24268:14268" # aip/trace
      - "24269:14269"
      - "19411:9411"
    networks:
      - jaeger-example
  hotrod-dev:
    image: jaegertracing/example-hotrod:latest
    ports:
      - "28080:8080"
    command: [ "all" ]
    environment:
      - JAEGER_AGENT_HOST=jaeger-dev
        # Note: if your application is using Node.js Jaeger Client, you need port 6832,
      #       unless issue https://github.com/jaegertracing/jaeger/issues/1596 is resolved.
      - JAEGER_AGENT_PORT=6831
    networks:
      - jaeger-example
    depends_on:
      - jaeger-dev

networks:
  jaeger-example: