server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
- job_name: containers
  static_configs:
    - targets:
        - localhost
      labels:
        log_from: static_pods
        __path__: /var/log/pods/*/*/*.log
  pipeline_stages:
    - docker: {}
    - match:
        selector: '{log_from="static_pods"}'
        stages:
          - regex:
              source: filename
              expression: "(?:pods)/(?P<namespace>\\S+?)_(?P<pod>\\S+)-\\S+?-\\S+?_\\S+?/(?P<container>\\S+?)/"
          - labels:
              namespace:
              pod:
              container:
    - match:
        selector: '{namespace!~"(default|kube-system)"}'
        action: drop
        drop_counter_reason: no_use
